#!/bin/bash

set -e

# Import Microsoft GPG key and add repo
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg

echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/mssql-release.list

apt-get update

# Install MS SQL ODBC driver
ACCEPT_EULA=Y apt-get install -y msodbcsql18
